all:
	$(MAKE) -C DAQLogger all;
	$(MAKE) -C Monitor all;
	$(MAKE) -C BestEffortDispatcher all;
	$(MAKE) -C Merger all;
	$(MAKE) -C MznHRTdcReader1 all;
	
clean:
	$(MAKE) -C DAQLogger clean;
	$(MAKE) -C Monitor clean;
	$(MAKE) -C BestEffortDispatcher clean;
	$(MAKE) -C Merger clean;
	$(MAKE) -C MznHRTdcReader1 clean;
